#!/bin/bash
#-----> Created by dici <-----#
y="\x1b["
R=$y"\e[37;1m"
B=$y"\e[36;1m"
D=$y"\e[35;1m"
ERROR=$y"38;05;204m"
A=$y"38;05;193m"
P="DiCi"

echo -e "$B[$D $P $B] $A  $R"
echo -e "$B[$D $P $B] $A ----------------------------- $R"
echo -e "$B[$D $P $B] $A  $R"
echo -e "$B[$D $P $B] $A        _ _      _  $R"
echo -e "$B[$D $P $B] $A       | (_)    (_) $R"
echo -e "$B[$D $P $B] $A     __| |_  ___ _  $R"
echo -e "$B[$D $P $B] $A    / _' | |/ __| | $R"
echo -e "$B[$D $P $B] $A   | (_| | | (__| | $R"
echo -e "$B[$D $P $B] $A    \__,_|_|\___|_| $R"
echo -e "$B[$D $P $B] $A  $R"
echo -e "$B[$D $P $B] $A  DiCi - Websystem Version 1.0 $R"
echo -e "$B[$D $P $B] $A  $R"
echo -e "$B[$D $P $B] $A  https://github.com/diciws $R"
echo -e "$B[$D $P $B] $A  https://gitlab.com/dici $R"
echo -e "$B[$D $P $B] $A  http://dici.ws $R"
echo -e "$B[$D $P $B] $A  https://twitter.com/diciws $R"
echo -e "$B[$D $P $B] $A  $R"
echo -e "$B[$D $P $B] $A ----------------------------- $R"
echo -e "$B[$D $P $B] $A  $R"
echo -e "$B[$D $P $B] $A Starting DiCi - Websystem installer $R"

sudo chmod -R 777 installer
sh ./installer/dependencies.sh

echo -e "$B[$D $P $B] $A ----------------------------- $R"
echo -e "$B[$D $P $B] $A PHP is now installed! $R"
echo -e "$B[$D $P $B] $A PHP5-GD is now installed! $R"
echo -e "$B[$D $P $B] $A Apache2 is now installed! $R"
echo -e "$B[$D $P $B] $A Git is now installed! $R"
echo -e "$B[$D $P $B] $A ----------------------------- $R"
echo -e " "
echo -e "$B[$D $P $B] $A Now importing DiCi - Websystem $R"

sh ./installer/importer.sh


echo -e "$B[$D $P $B] $A  $R"
echo -e "$B[$D $P $B] $A ----------------------------- $R"
echo -e "$B[$D $P $B] $A  $R"
echo -e "$B[$D $P $B] $A        _ _      _  $R"
echo -e "$B[$D $P $B] $A       | (_)    (_) $R"
echo -e "$B[$D $P $B] $A     __| |_  ___ _  $R"
echo -e "$B[$D $P $B] $A    / _' | |/ __| | $R"
echo -e "$B[$D $P $B] $A   | (_| | | (__| | $R"
echo -e "$B[$D $P $B] $A    \__,_|_|\___|_| $R"
echo -e "$B[$D $P $B] $A  $R"
echo -e "$B[$D $P $B] $A  DiCi - Websystem Version 1.0 $R"
echo -e "$B[$D $P $B] $A  $R"
echo -e "$B[$D $P $B] $A  https://github.com/diciws $R"
echo -e "$B[$D $P $B] $A  https://gitlab.com/dici $R"
echo -e "$B[$D $P $B] $A  http://dici.ws $R"
echo -e "$B[$D $P $B] $A  https://twitter.com/diciws $R"
echo -e "$B[$D $P $B] $A  $R"
echo -e "$B[$D $P $B] $A ----------------------------- $R"
echo -e "$B[$D $P $B] $A  $R"
echo -e "$B[$D $P $B] $A Starting DiCi - Websystem installer $R"